name: fasikasport
recipe: drupal9
config:
  webroot: .
services:
  node:
    type: node:13
    build:
      - npm install  
tooling:
  npm:
    service: node
  npx:
    service: node  
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node      
