<?php

function fasika_sport_theme_suggestions_form_alter(array &$suggestions, array $variables, $hook) {
  if (isset($variables['element']['#id'])) {
    $suggestions[] = 'form__' . str_replace('-', '_', $variables['element']['#id']);
  }
}

function fasika_sport_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'contact_message_feedback_form') {
    $form['name']['#title_display'] = 'invisible';
    $form['name']['#attributes']['class'] = [
      'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' 
    ];
    $form['mail']['#title_display'] = 'invisible';
    $form['mail']['#attributes']['class'] = [
      'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' 
    ];
    $form['subject']['widget'][0]['value']['#title_display'] = 'invisible';
    $form['subject']['widget'][0]['value']['#attributes']['class'] = [
      'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' 
    ];
    $form['message']['widget'][0]['value']['#title_display'] = 'invisible';
    $form['message']['widget'][0]['value']['#attributes']['class'] = [
      'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out'
    ];
    $form['actions']['submit']['#attributes']['class'] = [
      'text-white bg-orange-500 border-0 py-2 px-6 focus:outline-none hover:bg-black rounded text-lg'
    ];
    unset($form['actions']['preview']);
    //dump($form);exit;
  }
}    